### ISSUE TITLE
Timezone issues

### ISSUE THREAD

**Issue by dcunited001** [MAKEroanoke/makeroanoke.org#3]
Some of the dates in the posts' filenames and `date: 2024-01-12` don't match
don't match what's showing in the URL.  AFAIK, this is bc [Github actions builds
the site in UTC](https://dgmstuart.github.io/blog/2022/02/19/gotcha-jekyll-post-generated-with-wrong-date/). It only affects one post for now.

+ I can set specify the timezone in `_config.yml`
+ or we can continue to build the site in UTC and just forego the timezone (or
  time) in the `date:` field for posts. Then they'll all slide into the correct
  day.

To fix the post, we can add a permalink to it. I don't believe other posts will
break, since they're all past 5:00am. we should stick with whatever we decide to
do.

I tried attaching to the docker container and running this, but I can't
replicate it on my machine (which is UTC). neither changing `timezone:` key in
the `_config.yml` nor setting the `env` affect the `SafeYAML` parsing, so it
must be further into Jekyll or in basically-basic's `entry.html`.

```sh
cat <<EOPROG
require "safe_yaml/load";
puts YAML.load("date: 2024-01-12 23:42:08 -0400 ")
EOPROG | env TZ="UTC" ruby
# i ran this without a heredoc, so it may not work
```

**Comment by dcunited001** [comment]
As for the timezone thing, the problem is really just the date formatter
below.

We could fix it by importing the theme and changing it to `{{ post.date |
date_to_long_string }}`. Then we may not need the `permalink` for the posts in #9

These are the references from our site:

``` grep
site/events.md:15:      <span class="icon">{% include icon-calendar.svg %}</span> <time class="entry-time" datetime="{{ event.event_date | date_to_xmlschema }}">{{ event.event_date | date: "%B %-d, %Y" }}</time>
site/past-events.md:13:      <span class="icon">{% include icon-calendar.svg %}</span> <time class="entry-time" datetime="{{ event.event_date | date_to_xmlschema }}">{{ event.event_date | date: "%B %-d, %Y" }}</time>
```

And from our theme:

``` grep
_includes/footer.html:7:        <p>&copy; {{ site.time | date: '%Y' }} {{ site.title }}.</p>
_layouts/posts.html:8:  {% assign postsInYear = site.posts | group_by_exp: 'post', 'post.date | date: "%Y"' %}
_layouts/posts.html:18:{% assign postsByYear = site.posts | group_by_exp: 'post', 'post.date | date: "%Y"' %}
_includes/page-intro.html:24:            <time datetime="{{ page.date | date_to_xmlschema }}">{{ page.date | date: "%B %-d, %Y" }}</time>
_includes/entry.html:20:      <li><span class="icon">{% include icon-calendar.svg %}</span><time class="entry-time" datetime="{{ post.date | date_to_xmlschema }}">{{ post.date | date: "%B %-d, %Y" }}</time></li>
```

**Comment by slackish** [comment]
Just noting that `date_to_long_string` is at https://jekyllrb.com/docs/liquid/filters/  and would create`07 November 2008`.  Less clear on how that might impact these posts.  

What about this solution? https://stackoverflow.com/questions/70170735/change-timezone-for-github-pages

**Comment by slackish** [comment]
@dcunited001 Can you verify if this is fixed.  I meant to PR this, but it went to main. Change is at: https://github.com/MAKEroanoke/makeroanoke.org/commit/b1c68ec8c4e129b0385d4d89765e9cb19ba71847

**Comment by slackish** [comment]
Based on discord chat, we believe this is fixed.  Going to close; feel free to reopen if the issue comes back.
